/// Flutter icons FaceIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FaceIcon
///      fonts:
///       - asset: fonts/FaceIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FaceIcon {
  FaceIcon._();

  static const _kFontFam = 'FaceIcon';
  static const _kFontPkg = null;

  static const IconData face = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
