/// Flutter icons GIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GIcon
///      fonts:
///       - asset: fonts/GIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class GIcon {
  GIcon._();

  static const _kFontFam = 'GIcon';
  static const _kFontPkg = null;

  static const IconData search = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
