/// Flutter icons LinkedIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LinkedIcon
///      fonts:
///       - asset: fonts/LinkedIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class LinkedIcon {
  LinkedIcon._();

  static const _kFontFam = 'LinkedIcon';
  static const _kFontPkg = null;

  static const IconData linkedin = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
