/// Flutter icons OtherIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  OtherIcon
///      fonts:
///       - asset: fonts/OtherIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class OtherIcon {
  OtherIcon._();

  static const _kFontFam = 'OtherIcon';
  static const _kFontPkg = null;

  static const IconData icon_other_26 = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
