/// Flutter icons WhatIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WhatIcon
///      fonts:
///       - asset: fonts/WhatIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class WhatIcon {
  WhatIcon._();

  static const _kFontFam = 'WhatIcon';
  static const _kFontPkg = null;

  static const IconData whatsapp__1_ = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
